Fix fallthrough typo in XTF common/libc/vsnprintf.c
fallthrough in one case is missing the r.
This fails to suppress -Wimplicit-fallthrough warning with GCC7

common/libc/vsnprintf.c:388:19: error: this statement may fall through [-Werror=implicit-fallthrough=]
             flags |= SIGNED;
                   ^
common/libc/vsnprintf.c:390:9: note: here
         case 'u': /* Unsigned decimal. */
         ^~~~
cc1: all warnings being treated as errors

Signed-off-by: John Thomson <git@johnthomson.fastmail.com.au>
Reviewed-by: Andrew Cooper <andrew.cooper3@citrix.com>