Fix build with GCC 7
c/s e399b894f0 tried to make the function parameter to _ASM_EXTABLE_HANDLER()
visible to the compiler, for the benefit of LTO builds.  Unfortunately, GCC 7
doesn't like the chosen method, citing:

    error: asm operand 4 probably doesn’t match constraints [-Werror]

Instead, revert back to using the function by name, and make it visible to the
compiler by using the "X" constraint.

While making these changes, add a missing reference to
fpu-exception-emulation's probe_avx() and xsa-212's test_main().

Reported-by: Sergey Dyasli <sergey.dyasli@citrix.com>
Reported-by: Wei Liu <wei.liu2@citrix.com>
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
Tested-by: Wei Liu <wei.liu2@citrix.com>